version: '3.8'

services:
  project-management-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-management-php
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
      - mongodb
      - mysql
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - DB_HOST=mysql
      - DB_NAME=forbidden_codex
      - DB_USER=root
      - DB_PASS=rootpass
    develop:
      watch:
        - action: sync
          path: .
          target: /var/www/html
          ignore:
            - vendor/
            - node_modules/

  postgres:
    image: postgres:15
    container_name: project-management-postgres
    environment:
      POSTGRES_DB: project_management_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: project-management-mongodb
    environment:
      MONGO_INITDB_DATABASE: project_management_mongo
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mysql:
    image: mysql:8.0
    container_name: project-management-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: forbidden_codex
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  postgres_data:
  mongodb_data:
  mysql_data:
